# Generated by Django 3.0.7 on 2020-06-30 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrontUser',
        ),
    ]
